
 export const TYPE_SHIFT={
    DAY_SHIFT:'DIURNO',
    NIGHT_SHIFT:'NOCTURNO',
    DOMINICAL_SHIFT:'FESTIVO_DIURNO',
    NIGH_DOMINICAL_SHIFT:'FESTIVO_NOCTURNO'
}
export const COMISSIONS={
    COMISSION_DAY_SHIFT:'COMISION_DIURNO',
    COMISSION_NIGHT_SURCHARGE:'COMISION_NOCTURNO',
    COMISSION_HOLIDAY_SHIFT:'COMISION_DOMINICAL_DIURNO',
    COMISSION_SUNDAY_NIGHT:'COMISION_DOMINICAL_NOCTURNO'
}
export const EX_HOUR={
    DAYTIME_OVERTIME:'HORA_EXTRA_DIURNO',
    NIGHT_OVERTIME: 'HORA_EXTRA_NOCTURNO',
    DAYTIME_HOLIDAY: 'HORA_EXTRA_FESTIVO_DIURNO',
    NIGHT_HOLIDAY: 'HORA_EXTRA_FESTIVO_NOCTURNO'
}