
 export const TYPE_SHIFT={
    DAY_SHIFT:'DIURNO',
    NIGHT_SHIFT:'NOCTURNO',
    DOMINICAL_SHIFT:'FESTIVO_DIURNO',
    NIGH_DOMINICAL_SHIFT:'FESTIVA_NOCTURNO'
    //DEBE DE HABER RECARGO SI ES NOCTURNO Y DOMINICAL
    //PERO ESTOS SON APARTE SE SUMA EL TOTAL DE HORAS 
    //Y SE SACA LAS HORAS QUE SEAN NOCTURNAS Y DOMINICALES
    //PARA DARLE UN EXTRA
}
export const COMISSIONS={
    NIGHT_SURCHARGE:'NOCTURNO',
    SUNDAY:'RECARGO_DOMINICAL_DIURNO',
    SUNDAY_NIGHT:'RECARGO_DOMINICAL_NOCTURNO'
}