export const TYPE_SHIFT={
    DAY_SHIFT:'DIURNO',
    NIGHT_SHIFT:'NOCTURNO',
    DOMINICAL_SHIFT:'FESTIVO_DIURNO',
    NIGH_DOMINICAL_SHIFT:'FESTIVO_NOCTURNO'
}
export const COMISSIONS={
    NIGHT_SURCHARGE:'RECARGO_NOCTURNO',
    SUNDAY_NIGHT:'RECARGO_DOMINICAL_NOCTURNO'
}
export const EX_HOUR={
    DAYTIME_OVERTIME:'HORA_EXTRA_DIURNO',
    NIGHT_OVERTIME: 'HORA_EXTRA_NOCTURNO',
    DAYTIME_HOLIDAY: 'HORA_EXTRA_FESTIVO_DIURNO',
    NIGHT_HOLIDAY: 'HORA_EXTRA_FESTIVO_NOCTURNO'
}